---
# Service
apiVersion: v1
kind: Service
metadata:
  name: demo-hello-world
spec:
  selector:
    app: demo-hello-world
  ports:
    - port: 80
      targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-hello-world
  template:
    metadata:
      labels:
        app: demo-hello-world
    spec:
      containers:
        - name: demo-hello-world
          image: k33g/demo-hello-world:0.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-hello-world
spec:
  rules:
    - host: demo-hello-world.17d4505a-657f-4bbb-9779-8868f287b6a6.k8s.civo.com
    #- host: demo-hello-world.74.220.29.63.sslip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: demo-hello-world
              port: 
                number: 80
